// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Demo(arg1) {
	return window['go']['main']['App']['Demo'](arg1)
}

export function Greet(arg1) {
	return window['go']['main']['App']['Greet'](arg1)
}
